var jvh=jvh||{};jvh.destinations={myself:null,regionTempChart:0,latitude:0,longitude:0,pageClass:"",destTextObj:null,villaBlocksRun:!1,destSettings:{id:0,destName:"",tempData:[],rainData:[],months:[],mapDisclaimer:"",resortGallery:[],resortGalleryTags:[]},init:function(){var e=jvh.destinations;
    if(e.destSettings.mapDisclaimer=jvh.data.destMapDisclaimer||"",$("body").hasClass("all-destinations")||(e.settings=$.extend(e.destSettings,destSettings),destSettings=null),e.destPageInit.init(),jvh.core.accomFilterOnClick(),e.map.mapFilterOnClick(),e.windowResize(),"resort"==jvh.destinations.pageClass||"holiday-resort"==jvh.destinations.pageClass)e.resortInit();
    else{var t={items:1,center:!1,loop:!1,nav:!1,dots:!0,margin:10,navText:["",""],responsive:{480:{items:2}}},a=$("ul.popular");
    a.data("settings",t),a.each(function(){var e=$(this);jvh.core.owlCarousel.removeOwlAtResize(e,"mobile",e.data("settings"))
    })}$(window).on("scroll",debounce(jvh.destinations.delayedScroll,200)),e.delayedScroll(),jvh.destinations.searchBox(),jvh.destinations.adobeTrackingEnable(),jvh.destinations.destinationMedia()
    },adobeTrackingEnable:function(){const e=document.querySelector(".container"),t="Destination-interaction";
    jvh.core.tracking.adobeAutoTrack(e,t),jvh.core.tracking.adobeLazyTrack(e,t),jvh.destinations.trackDestinationCarousel(),jvh.destinations.destinationQuickSearch(),jvh.destinations.customAdobeTracking(),jvh.destinations.customLazyAdobeTracking()
    },trackDestinationCarousel:function(){const e=document.querySelector(".owl-carousel.owl-carousel-destination");
    e&&(jvh.destinations.trackCarouselNavigation(e),jvh.destinations.trackCarouselBlocks(e),jvh.destinations.trackCarouselDots(e))
    },destinationQuickSearch:function(){const e=document.querySelector(".searchbar-dest-list"),t={childList:!0,subtree:!0},a=function(e){e.forEach(function(e){"childList"===e.type&&[].slice.call(e.addedNodes).forEach(function(e,t){e.addEventListener("click",function(){const a="["+e.innerHTML+"]|["+t+"] Searched";
    jvh.core.tracking.trackAdobeEvent("Destination-interaction","Quick Search",a)})})})},i=new MutationObserver(a);
    i.observe(e,t)},trackCarouselNavigation:function(e){var t=1;const a=jvh.destinations.destSettings.destName+" Content Carousel",i=e.querySelectorAll(".owl-item:not(.cloned)").length,o=e.querySelector(".owl-next"),s=e.querySelector(".owl-prev");
    $(e).on("dragged.owl.carousel",function(i){const o=i.relatedTarget._drag.direction,s=e.querySelectorAll(".owl-item:not(.cloned)");
    Array.from(s).find(function(e){if(e.classList.contains("active")){const i=e.querySelector("a").getAttribute("data-index"),s="left"===o?"Next ["+i+"] Dragged":"Prev ["+i+"] Dragged";
    return t=i,jvh.core.tracking.trackAdobeEvent("Destination-interaction",a,s),!0}return!1})}),o&&o.addEventListener("click",function(){t++,t>i&&(t=1);
    const e="Next ["+t+"] Clicked";jvh.core.tracking.trackAdobeEvent("Destination-interaction",a,e)}),s&&s.addEventListener("click",function(){t--,1>t&&(t=i);
    const e="Prev ["+t+"] Clicked";jvh.core.tracking.trackAdobeEvent("Destination-interaction",a,e)})},trackCarouselBlocks:function(e){const t=e.querySelectorAll(".owl-item a");
    [].slice.call(t).forEach(function(e){e.addEventListener("click",function(){const t=e.getAttribute("data-index"),a=e.children[0].innerHTML,i=jvh.destinations.destSettings.destName+" Content Carousel",o=a+" ["+t+"] Clicked";
    jvh.core.tracking.trackAdobeEvent("Destination-interaction",i,o)})})},trackCarouselDots:function(e){const t=e.querySelectorAll(".owl-dot");
    [].slice.call(t).forEach(function(e,t){e.addEventListener("click",function(){const e=jvh.destinations.destSettings.destName+" Content Carousel",a="Dot ["+(t+1)+"] Clicked";
    jvh.core.tracking.trackAdobeEvent("Destination-interaction",e,a)})})},customAdobeTracking:function(){const e=document.querySelectorAll(".destination-block"),t=document.querySelectorAll(".info-section"),a=document.querySelectorAll(".chevron-link.black.dest-link"),i=document.querySelectorAll(".chevron-link.black.villas-link"),o=document.getElementById("destSearchBox"),s=document.querySelectorAll(".breadcrumb a");
    [].slice.call(e).forEach(function(e){e.addEventListener("mouseenter",function(){const t=e.dataset.destType.charAt(0).toUpperCase()+e.dataset.destType.slice(1),a=e.dataset.resort+" "+t+" Block";
    jvh.core.tracking.trackAdobeEvent("Destination-interaction",a,"Hover "+e.dataset.resort)})}),[].slice.call(a).forEach(function(e){e.addEventListener("click",function(){const t=e.dataset.destType.charAt(0).toUpperCase()+e.dataset.destType.slice(1),a=e.dataset.resort+" "+t+" Block";
    jvh.core.tracking.trackAdobeEvent("Destination-interaction",a,"Explore "+e.dataset.resort)})}),[].slice.call(t).forEach(function(e){e.addEventListener("click",function(){const t=e.dataset.destType.charAt(0).toUpperCase()+e.dataset.destType.slice(1),a=e.dataset.resort+" "+t+" Block";
    jvh.core.tracking.trackAdobeEvent("Destination-interaction",a,e.dataset.trackAction)})}),[].slice.call(i).forEach(function(e){e.addEventListener("click",function(){const t=e.dataset.destType.charAt(0).toUpperCase()+e.dataset.destType.slice(1),a=e.dataset.resort+" "+t+e.dataset.destType.slice(1)+" Block";
    jvh.core.tracking.trackAdobeEvent("Destination-interaction",a,"View villas "+e.dataset.resort)})}),o.addEventListener("keyup",function(e){const t=13;
    e.keyCode===t&&jvh.core.tracking.trackAdobeEvent("Destination-interaction","Destination search box","Search")
    }),[].slice.call(s).forEach(function(e){e.addEventListener("click",function(){const t=jvh.destinations.settings.destName+" Breadcrumb",a="back to "+e.childNodes[0].innerText+" Clicked";
    jvh.core.tracking.trackAdobeEvent("breadcrumb",t,a)})})},customLazyAdobeTracking:function(){const e=document.querySelector(".james-popular ul"),t=document.querySelector(".new-villas ul"),a={childList:!0,subtree:!0},i=function(e,t){e.forEach(function(e){"childList"===e.type&&([].slice.call(e.addedNodes).forEach(function(e){const t=e.getAttribute("data-track-action"),a=e.getAttribute("data-track-name");
    e.addEventListener("click",function(){jvh.core.tracking.trackAdobeEvent("Destination-interaction",a,t)
    })}),t.disconnect())})},o=new MutationObserver(i);e&&o.observe(e,a),t&&o.observe(t,a)},delayedScroll:function(){if(jvh.destinations.map.mapRun||"mobile"==jvh.core.viewport||jvh.core.isInView("section.map-content",200)&&(jvh.destinations.map.mapRun=!0,jvh.destinations.map.loadMap()),"region"==jvh.destinations.pageClass&&jvh.destinations.destSettings.tempData!==void 0&&jvh.destinations.destSettings.rainData!==void 0&&($(".temp-rainfall-chart").hasClass("loaded")||(jvh.core.isInView(".temp-rainfall-chart",200)&&$(".temp-rainfall-chart").addClass("loaded"),jvhWaitForJs(["chart.min"],jvh.destinations.createChart))),"all-destinations"!=jvh.destinations.pageClass&&"resort"!=jvh.destinations.pageClass&&"holiday-resort"!=jvh.destinations.pageClass){var e=$("section.new-villas");
    jvh.core.isInView(".auto-villa-blocks.accom-loaded",200)&&(jvh.destinations.villaBlocksRun=!0,0==$("ul.auto-villa-blocks li:not(.filler-li)",e).length&&e.addClass("hidden"))
    }},windowResize:function(){$(window).resize(function(){if("resort"==jvh.destinations.pageClass||"holiday-resort"==jvh.destinations.pageClass){var e=jvh.destinations;
    e.events.fillerEventSquares(".psuedo-calendar"),e.events.fillerEventSquares(".psuedo-hr-calendar")}})
    },destPageInit:{initIteration:0,init:function(){var e=jvh.destinations,t=$("body");t.hasClass("resort")?(jvh.destinations.pageClass="resort",jvh.core.trackingType=jvh.destinations.destSettings.destName+" Resort Landing Page"):t.hasClass("holiday-resort")?(jvh.destinations.pageClass="holiday-resort",jvh.core.trackingType=jvh.destinations.destSettings.destName+" Holiday Resort Landing Page"):t.hasClass("region")?(jvh.destinations.pageClass="region",jvh.core.trackingType=jvh.destinations.destSettings.destName+" Region Landing Page"):t.hasClass("region-group")?(jvh.destinations.pageClass="region-group",jvh.core.trackingType=jvh.destinations.destSettings.destName+" Region Group Landing Page"):t.hasClass("country")?(jvh.destinations.pageClass="country",jvh.core.trackingType=jvh.destinations.destSettings.destName+" Country Landing Page"):t.hasClass("all-destinations")&&(jvh.destinations.pageClass="all-destinations",jvh.core.trackingType="All Destinations Landing Page"),jvh.destinations.clickEvents(),"country"!=jvh.destinations.pageClass&&"all-destinations"!=jvh.destinations.pageClass&&e.loadGeoFunctions()
    }},loadGeoFunctions:function(){var e=jvh.destinations;$(document).on("accomLoaded",function(){resorts2[e.destSettings.id]!==void 0&&("resort"==jvh.destinations.pageClass?(latitude=resorts2[e.destSettings.id].lat,longitude=resorts2[e.destSettings.id].lng):"holiday-resort"==jvh.destinations.pageClass?(latitude=resorts2[e.destSettings.id].lat,longitude=resorts2[e.destSettings.id].lng):"region"==jvh.destinations.pageClass?(latitude=regions2[e.destSettings.id].lat,longitude=regions2[e.destSettings.id].lng):"region-group"==jvh.destinations.pageClass&&(latitude=regionGroups2[e.destSettings.id].lat,longitude=regionGroups2[e.destSettings.id].lng)),"undefined"!=typeof latitude&&"undefined"!=typeof longitude&&(e.latitude=latitude,e.longitude=longitude)
    })},clickEvents:function(){$(".sort-by .alphabetical").click(function(e){e.preventDefault(),jvh.destinations.destinationSorter.sort("alphabetical")
    }),$(".sort-by .popular").click(function(e){e.preventDefault(),jvh.destinations.destinationSorter.sort("popular")
    }),$(".map-terms").click(function(){jvh.core.showInnerModal($("section.map-content"),'<div class="caveats"><h2>Important Information</h2>'+jvh.destinations.destSettings.mapDisclaimer+"</div>",$(this))
    }),$(".accordion-menu h3").click(function(){var e=this.parentElement.classList;e.toggle("active");var t=e.contains("active")?"Expanded":"Collapsed";
    jvh.core.tracking.trackAdobeEvent("Destination-interaction",this.getAttribute("data-track-action"),t)
    }),$(".map-content").on("click",".beach-golf-container button.close",function(e){e.preventDefault(),jvh.destinations.closeBeachGolf()
    }),$(".map-content a.map-load-mobile").click(function(e){e.preventDefault(),jvh.destinations.map.loadMap()
    }),$(".mob-filter-toggle").click(function(){thisItem=$(this),thisItem.hasClass("open")?(thisItem.removeClass("open"),$("#accomFilter, #accomFilter > ul > li, #mapFilter, #mapFilter > ul > li, .beach-golf-container").removeClass("active")):($(".beach-golf-container").removeClass("active"),thisItem.addClass("open"),$("#mapFilter").addClass("active"))
    }),$(document).on("viewport.changed",function(e,t){"mobile"==jvh.core.viewport?($("#mapPanel, #mapFilter, #accomFilter, .beach-golf-container, .mob-filter-toggle, .mob-map-label").removeClass("active"),$("#mapPanel").empty()):"mobile"==t&&($("#mapPanel, #mapFilter, #accomFilter, .beach-golf-container, .mob-filter-toggle, .mob-map-label").removeClass("active"),jvh.core.closeModal(),$("#modalContent").empty(),jvh.core.mapFirstRun=!0,jvh.destinations.map.loadMap(),$("#mapFilter").addClass("active")),$("ul.popular").each(function(){var e=$(this);
    jvh.core.owlCarousel.removeOwlAtResize(e,"mobile",e.data("settings"))})})},searchBox:function(){$(".dest-search-box").on("click",".searchbar-dest-list li:not(.no-link)",function(e){var t=$(this);
    e.stopPropagation(),13==e.keyCode&&e.preventDefault(),$(".dest-search-box .search-dest").val(t.text()),jvh.searchbar.regionListContent(t)
    }),$(".dest-search-box .close").bind("click",function(){return jvh.searchbar.fnHideShowPanels(this.id,!1,".dest-search-box"),!1
    }),jvh.destinations.destTextObj=$(".dest-search-box .search-dest"),jvh.destinations.destTextObj.bind("keydown",function(e){jvh.searchbar.fnTextSearch(e,"down",".dest-search-box")
    }),jvh.destinations.destTextObj.bind("keyup",function(e){jvh.searchbar.fnTextSearch(e,"up",".dest-search-box")
    }),jvh.destinations.destTextObj.focusin(function(){var e=$(this);e.select()}),jvh.destinations.destTextObj.bind({focus:function(){$(this).parent().addClass("focus"),jvh.core.tracking.trackEvent(jvh.core.trackingType,"Focus in","Destination Search Box",null)
    },blur:function(){return jvh.core.tracking.trackEvent(jvh.core.trackingType,"Focus out","Destination Search Box",null),window.setTimeout(function(){jvh.searchbar.fnHideShowPanels(this.id,!1,".dest-search-box")
    },1e3),!1}}),jvh.destinations.fnPlaceholder()},destinationMedia:function(){const e=document.querySelector(".destination-media-image-wrapper"),t=8,a=7,i=jvh.destinations.destSettings.galleryJson;
    var o;o=void 0!=i?JSON.parse(i):!1;const s=o&&o.videoUrl&&""!==o.videoUrl;if(s){const n=o.videoUrl.indexOf("<iframe")>=0,r=o.videoUrl.indexOf("youtu.be")>=0,c=o.videoUrl.indexOf("youtube.com")>=0||r,l=document.querySelector(".destination-media-video-wrapper");
    if(n){const d=document.createRange().createContextualFragment(o.videoUrl).firstChild;d.removeAttribute("width"),d.removeAttribute("height"),d.classList.add("destination-media-video"),l.appendChild(d)
    }else if(c){const v=!o.videoUrl.indexOf("/embed")>=0;v&&(o.videoUrl=jvh.destinations.setupYoutubeLink(o.videoUrl,r));
    const d=document.createElement("iframe");d.classList.add("destination-media-video"),d.src=o.videoUrl,d.setAttribute("allowfullscreen",""),l.appendChild(d)
    }else{const h=document.createElement("video");h.classList.add("destination-media-video"),h.controlsList="nodownload",h.src=o.videoUrl,h.setAttribute("controls",""),l.appendChild(h)
    }}const m=o&&o.imagesUrls&&""!==o.imagesUrls;if(m){const p=jvh.destinations.createImagesGalleryArray(o.imagesUrls).filter(function(e){return""!=e
    });for(imageNumber=0;t>imageNumber;imageNumber++){const u=p[imageNumber];if(u){const g=document.createElement("button"),f=jvh.destinations.createImage(u);
    g.classList.add("destination-media-image"),g.classList.add("destination-media-extend"),g.appendChild(f),e.appendChild(g),imageNumber===a&&p.length>t&&jvh.destinations.createExtendGalleryButton(g,p,t)
    }else{const b=document.createElement("div");b.classList.add("destination-media-image"),e.appendChild(b)
    }}jvh.destinations.setExtendGalleryButtonClickEvent(p)}},setupYoutubeLink:function(e,t){if(t||0>e.indexOf("watch?v=")){const a=/[^/]*$/.exec(e)[0];
    return"https://www.youtube.com/embed/"+a}return e.replace("watch?v=","embed/")},createImagesGalleryArray:function(e){const t=e.replace(/\s+/g,"");
    return t.split(",")},createImage:function(e){const t=new Image;return t.src=e,t.alt="Destination image",t
    },createExtendGalleryButton:function(e,t,a){const i=t.length-a,o='<div class="destination-media-extend-wrapper"><p class="destination-media-extend-info destination-media-extend-info-big">+'+i+"</p>"+'<p class="destination-media-extend-info">Photos</p>'+"</div>";
    e.insertAdjacentHTML("beforeend",o)},setExtendGalleryButtonClickEvent:function(e){const t=document.querySelectorAll(".destination-media-extend");
    Array.prototype.slice.call(t,0).forEach(function(t){t.addEventListener("click",function(){jvh.core.gallery.fnShowGallery({images:e})
    })})},fnPlaceholder:function(){"mobile"==jvh.core.viewport?jvh.destinations.destTextObj.attr("placeholder",jvh.destinations.destTextObj.data("short-placeholder")):jvh.destinations.destTextObj.attr("placeholder",jvh.destinations.destTextObj.data("long-placeholder"))
    },destinationSorter:{alphabetical:function(e,t){var a=$(e),i=$(t),o=a.data("dest-name"),s=i.data("dest-name"),n=o.toLowerCase().replace("the ",""),r=s.toLowerCase().replace("the ","");
    return r>n?-1:n>r?1:0},popular:function(e,t){var a=$(e),i=$(t);return parseInt(i.data("count-villas"))-parseInt(a.data("count-villas"))
    },sort:function(e){var t=$(".destination-blocks .image-text-two-links");$(".sort-by button").removeClass("active"),"alphabetical"==e?(t.find("> li").sort(jvh.destinations.destinationSorter.alphabetical).appendTo(t),$(".sort-by .alphabetical").addClass("active")):(t.find("> li").sort(jvh.destinations.destinationSorter.popular).appendTo(t),$(".sort-by .popular").addClass("active")),jvh.core.images.lazyLoad()
    }},resortInit:function(){var e=jvh.destinations;$("button.photo-sprite").click(function(){jvh.core.gallery.fnShowGallery({images:jvh.destinations.destSettings.resortGallery,tags:jvh.destinations.destSettings.resortGalleryTags})
    }),$("#resort-info .hr-map").click(function(e){e.preventDefault();var t=$(this).data("map-image"),a=new Image,i=$(this).data("map-image-key");
    a.onload=function(){if(i!==void 0){var e=new Image;e.onload=function(){var o;"mobile"===jvh.core.viewport?o="max-width:"+a.width+"px;":(o="max-width:calc(100% - "+(e.width+20)+"px);",o+="margin-right:"+(e.width+20)+"px;");
    var s='<img src="'+jvh.core.settings.imageDomain+t+'" alt="Resort map of '+jvh.destinations.destSettings.destName+'" class="hr-map-image" style="'+o+'" />';
    s+='<img src="'+jvh.core.settings.imageDomain+i+'" alt="Resort map key of '+jvh.destinations.destSettings.destName+'" class="hr-map-key-image" />',jvh.core.showModal(s)
    },e.src=jvh.core.settings.imageDomain+i}else jvh.core.showModal('<img src="'+jvh.core.settings.imageDomain+t+'" alt="Resort map of '+jvh.destinations.destSettings.destName+'" class="hr-map-image" />')
    },a.src=jvh.core.settings.imageDomain+t,jvh.core.tracking.trackEvent(jvh.core.trackingType,"Holiday Resort map opened ","Resort links")
    }),$(".accordion .item-tab, .mobile-accordion .option-replacement li").click(function(){var e,t,a="";
    if("mobile"==jvh.core.viewport){var e=$("#accordian");a=e.val()}else e=$(this),$(".accordion .item-tab").removeClass("active"),e.closest(".item-tab").addClass("active"),a=e[0].id;
    $(".resort-tabs > div").removeClass("active");var i=$("."+a);i.addClass("active"),"mobile"!=jvh.core.viewport?($("ul.resort-sub-tabs li",i).removeClass("active"),$("ul.resort-sub-tabs li:first-of-type",i).addClass("active"),t=$("."+$("ul.resort-sub-tabs li:first-of-type button",i).attr("id"))):($("#resort-sub-tabs option:first",i).prop("selected",!0),$(".mobile-sub-tabs .option-replacement li",i).removeClass("selected"),$(".mobile-sub-tabs .option-replacement li:first",i).addClass("selected"),t=$("."+$("#resort-sub-tabs").val()),$("#resort-sub-tabs option:first",t).prop("selected",!0),$(".mobile-sub-tabs .option-replacement li",t).removeClass("selected"),$(".mobile-sub-tabs .option-replacement li:first",t).addClass("selected")),$(".resort-tab-content",i).removeClass("active"),$(".resort-tab-content:first",i).addClass("active"),t.addClass("active"),$("#resort-sub-tabs option:first",t).prop("selected",!0),t.find(".resort-tab-content").removeClass("active"),t.find(".resort-tab-content:first").addClass("active"),"events-content"==a&&("mobile"!=jvh.core.viewport?$(".psuedo-calendar ul.active li.month, .psuedo-calendar ul.active li.day").each(function(e){var t=$(this);
    window.setTimeout(function(){t.addClass("visible")},100*e)}):$("#eventViewSelect option:first").trigger("change")),jvh.core.images.lazyLoad(i)
    }),$("ul.resort-sub-tabs li button, .mobile-sub-tabs .option-replacement li").click(function(){var e=$(this),t="";
    if("mobile"==jvh.core.viewport){t=e.data("value");var a=e.closest("#resortSubTabs"),i=a.parent()}else{t=e[0].id;
    var a=e.closest("ul.resort-sub-tabs"),i=a.parent();$("li",a).removeClass("active")}$(".resort-tab-content",i).removeClass("active"),e.closest("li").addClass("active");
    var o=$("."+t);o.addClass("active"),jvh.core.images.lazyLoad(o),"mobile"==jvh.core.viewport?($("#resort-sub-tabs option:first",o).prop("selected",!0),$(".mobile-sub-tabs .option-replacement li",o).removeClass("selected"),$(".mobile-sub-tabs .option-replacement li:first",o).addClass("selected")):($("ul.resort-sub-tabs li",o).removeClass("active"),$("ul.resort-sub-tabs li:first-of-type",o).addClass("active"));
    var s=$(".resort-tab-content",o);s.removeClass("active"),$(".resort-tab-content:first",o).addClass("active"),s.find(".resort-tab-content").removeClass("active"),s.find(".resort-tab-content:first").addClass("active")
    }),window.location.hash&&window.location.hash.indexOf("destPromos")>=0&&window.setTimeout(function(){jvh.core.goToAnchor("destPromos","",1e3)
    },1e3);var t={items:1,center:!0,loop:!0,nav:!0,dots:!0,navText:["",""],autoWidth:!1},a=$("ul.resort-promos");
    a.data("settings",t),"mobile"==jvh.core.viewport&&("mobile"==jvh.core.viewport&&$("li.promo-filler",a).remove(),$("li",a).length>2&&a.owlCarousel(t)),$(document).on("viewport.changed",function(){$(".resort-tabs > div").removeClass("active"),$(".item-tab").removeClass("active"),$(".accom-content").addClass("active"),$(".item-tab:first-of-type").addClass("active"),$("#accordian").prop("selectedIndex",0),e.resortAccomSection.showAccom(),e.resortAccomSection.init(0),jvh.destinations.events.buildLists();
    var t=$("ul.resort-promos");$("li",t).length>2&&("mobile"==jvh.core.viewport&&$("li.promo-filler",t).remove(),jvh.core.owlCarousel.removeOwlAtResize(t,"mobile",t.data("settings")));
    var a=$(".mob-events");a.each(function(){var e=$(this);$("li",e).length>2&&jvh.core.owlCarousel.removeOwlAtResize(e,"mobile",e.data("settings"))
    }),"mobile"===jvh.core.viewport&&$(".hr-map-image").length>0&&($(".hr-map-image").css("margin-right","0px"),$(".hr-map-image").css("max-width","none"))
    }),jvh.destinations.resortInView()},createChart:function(){0!=jvh.destinations.regionTempChart&&jvh.destinations.regionTempChart.destroy(),Chart.defaults.global.responsive=!0,Chart.defaults.global.tooltipXPadding=12,Chart.defaults.global.scaleLineColor="rgba(0,0,0,0.3)",Chart.defaults.global.scaleFontColor="#000",Chart.defaults.global.animationEasing="easeOutQuint";
    const e=$("#regionTempChart").get(0);if(e){var t=e.getContext("2d"),a={scaleShowGridLines:!1};if("View Temperature"==$("#regionTempChange").html()||""==$("#regionTempChange").html()){$("#regionTempChange").html("View Rainfall"),$("#scale-label").html("°C"),Chart.defaults.global.tooltipTemplate="<%if (label){%><%=label%>: <%}%><%= value %> °C";
    var i={labels:jvh.destinations.destSettings.months,datasets:[{label:"Temperature in °C",fillColor:"rgba(244,223,122,1)",strokeColor:"rgba(220,220,220,0)",pointColor:"rgba(000,000,000,1)",pointStrokeColor:"#fff",pointHighlightFill:"#000",pointHighlightStroke:"rgba(0,0,0,1)",data:jvh.destinations.destSettings.tempData}]}
    }else{$("#regionTempChange").html("View Temperature"),$("#regionTempChange").attr("data-track-action","View Temperature"),$("#scale-label").html("mm"),Chart.defaults.global.tooltipTemplate="<%if (label){%><%=label%>: <%}%><%= value %> mm",Chart.defaults.global.scaleStepWidth=20,Chart.defaults.global.scaleStartValue=0;
    var i={labels:jvh.destinations.destSettings.months,datasets:[{label:"Rainfall in mm",fillColor:"rgba(24,185,255,1)",strokeColor:"rgba(255,0,0,0)",pointColor:"rgba(000,000,000,1)",pointStrokeColor:"#fff",pointHighlightFill:"#000",pointHighlightStroke:"rgba(0,0,0,1)",data:jvh.destinations.destSettings.rainData}]}
    }jvh.destinations.regionTempChart=new Chart(t).Line(i,a);var o=[];for(index=0;jvh.destinations.destSettings.months.length>index;++index)o.push(jvh.destinations.destSettings.months[index].substring(0,1));
    jvh.destinations.regionTempChart.scale.xLabels=o,jvh.destinations.regionTempChart.update()}},map:{mapReady:!1,mapData:null,beachesLoaded:!1,beaches:[],activitiesLoaded:!1,activities:[],nightlifeLoaded:!1,nightlife:[],restaurantLoaded:!1,restaurant:[],shoppingLoaded:!1,shopping:[],poiLoaded:!1,poi:[],snapsLoaded:!1,snaps:[],villasLoaded:!1,villas:[],loadMap:function(){var e=jvh.destinations;
    jvh.core.waitForTrigger("accomLoaded",typeof accomInfoLoaded,"DataForMap",function(){"mobile"==jvh.core.viewport?(jvh.core.showModal(null,!1,null,!1,"dest-map"),jvh.core.mapFirstRun=!0):$("#mapPanel").addClass("active"),jvh.core.mapFirstRun&&("all-destinations"==jvh.destinations.pageClass?jvh.core.load.loadMap(jvh.destinations.map.initAllDest):"country"==jvh.destinations.pageClass?jvh.core.load.loadMap(jvh.destinations.map.initCountry):"region"==jvh.destinations.pageClass?jvh.core.load.loadMap(jvh.destinations.map.initRegion):"region-group"==jvh.destinations.pageClass?jvh.core.load.loadMap(jvh.destinations.map.initRegionGroup):jvh.core.load.loadMap(jvh.destinations.map.initResort),"mobile"==jvh.core.viewport&&$(".mob-map-label").addClass("active"),"all-destinations"!=jvh.destinations.pageClass&&(jvh.destinations.map.getMapData(e.destSettings.id,jvh.destinations.pageClass),"mobile"==jvh.core.viewport?($(".mob-filter-toggle").addClass("active"),$("#mapFilter").addClass("active")):$("#mapFilter").addClass("active")))
    })},getMapData:function(e,t){var a="/ajax/populate-map-data.ajax",i="";("resort"==t||"holiday-resort"==t)&&(i=e,e=0),$.ajax({url:a,cache:!0,type:"GET",timeout:1e4,data:{id:e,destinationType:t,resortId:i},dataType:"json",success:function(e){if(e!==void 0&&null!=e){jvh.destinations.map.mapData=e;
    var t=$("#map5"),a=$("#map6"),i=$("#map7"),o=$("#map10"),s=$("#map8"),n=$("#map9"),r=$("#map11");jvh.destinations.map.mapData.beaches.length>0&&0==$(".beach-golf-container.beach").length&&jvh.destinations.map.beachCarousel(jvh.destinations.map.mapData.beaches),jvh.destinations.map.mapData.golfCourses.length>0&&0==$(".beach-golf-container.golf").length&&jvh.destinations.map.golfCarousel(jvh.destinations.map.mapData.golfCourses);
    for(var c=0;jvh.destinations.map.mapData.sharedComments.length>c;c++)switch(jvh.destinations.map.mapData.sharedComments[c].categoryId){case 3:t.removeClass("disabled"),jvh.destinations.map.beaches.push(jvh.destinations.map.mapData.sharedComments[c]);
    break;case 4:a.removeClass("disabled"),jvh.destinations.map.activities.push(jvh.destinations.map.mapData.sharedComments[c]);
    break;case 7:i.removeClass("disabled"),jvh.destinations.map.nightlife.push(jvh.destinations.map.mapData.sharedComments[c]);
    break;case 8:s.removeClass("disabled"),jvh.destinations.map.restaurant.push(jvh.destinations.map.mapData.sharedComments[c]);
    break;case 9:n.removeClass("disabled"),jvh.destinations.map.shopping.push(jvh.destinations.map.mapData.sharedComments[c]);
    break;case 10:o.removeClass("disabled"),jvh.destinations.map.poi.push(jvh.destinations.map.mapData.sharedComments[c]);
    break;case 11:r.removeClass("disabled"),jvh.destinations.map.snaps.push(jvh.destinations.map.mapData.sharedComments[c])
    }}},error:function(e,t,a){console.log(a)}})},bindClick:function(){$("#mapPanel").on("click",".jvh-map a.cta, .sub-dests li a",function(e){e.preventDefault(),jvh.core.tracking.trackOutbound(this.href,jvh.core.trackingType,$(this).data("track-name")+" map cta","Tile CTA",this.href)
    })},initAllDest:function(){jvh.map.showRegionCountryMap(0,null,null,null,null),jvh.destinations.map.bindClick()
    },initCountry:function(){jvh.map.showRegionCountryMap(4,jvh.destinations.destSettings.id,null,null,null),jvh.destinations.map.bindClick()
    },initRegionGroup:function(){jvh.map.showRegionCountryMap(5,null,jvh.destinations.destSettings.id,null,null),jvh.destinations.map.bindClick()
    },initRegion:function(){jvh.map.showRegionCountryMap(6,null,null,jvh.destinations.destSettings.id,null),jvh.destinations.map.bindClick()
    },initResort:function(){jvh.map.showRegionCountryMap(7,null,null,null,jvh.destinations.destSettings.id),jvh.destinations.map.bindClick()
    },mapFilterOnClick:function(){$("#mapFilter ul li:not(.map-terms)").click(function(){var e=$(this),t=e.data("filter-type"),a="";
    e.hasClass("disabled")||(e.hasClass("active")?(show=!1,e.removeClass("active")):(show=!0,e.addClass("active")),1==t&&"undefined"!=typeof villas1?(a=villas1,$("#accomFilter").toggleClass("active"),$("#accomFilter li").removeClass("active")):3==t&&jvh.destinations.map.beaches!==void 0?(a=jvh.destinations.map.beaches,jvh.destinations.map.beachesLoaded||(jvh.map.showSharedComments(a),jvh.destinations.map.beachesLoaded=!0)):4==t&&jvh.destinations.map.activities!==void 0?(a=jvh.destinations.map.activities,jvh.destinations.map.activitiesLoaded||(jvh.map.showSharedComments(a),jvh.destinations.map.activitiesLoaded=!0)):7==t&&jvh.destinations.map.nightlife!==void 0?(a=jvh.destinations.map.nightlife,jvh.destinations.map.nightlifeLoaded||(jvh.map.showSharedComments(a),jvh.destinations.map.nightlifeLoaded=!0)):10==t&&jvh.destinations.map.poi!==void 0?(a=jvh.destinations.map.poi,jvh.destinations.map.poiLoaded||(jvh.map.showSharedComments(a),jvh.destinations.map.poiLoaded=!0)):8==t&&jvh.destinations.map.restaurant!==void 0?(a=jvh.destinations.map.restaurant,jvh.destinations.map.restaurantLoaded||(jvh.map.showSharedComments(a),jvh.destinations.map.restaurantLoaded=!0)):9==t&&jvh.destinations.map.shopping!==void 0?(a=jvh.destinations.map.shopping,jvh.destinations.map.shoppingLoaded||(jvh.map.showSharedComments(a),jvh.destinations.map.shoppingLoaded=!0)):11==t&&jvh.destinations.map.snaps!==void 0&&(a=jvh.destinations.map.snaps,jvh.destinations.map.snapsLoaded||(jvh.map.showSharedComments(a),jvh.destinations.map.snapsLoaded=!0)),t!==void 0&&null!=t&&a!==void 0&&null!=a&&(jvh.map.hideShowItems(a,show),$("#mapFilter ul li.active").length>0?(jvh.map.mapZoomCustom=null,jvh.map.hideShowItems(resorts1,!1),jvh.map.hideShowItems(regions1,!1),jvh.map.hideShowItems(regionGroups1,!1),jvh.map.hideShowItems(countries1,!1),jvh.map.resizeBounds()):jvh.destinations.map.showDestCentred(),jvh.core.tracking.trackEvent(jvh.core.trackingType,"Map filter "+e.data("track-name")+" toggled","Page Navigation")))
    })},showDestCentred:function(){jvh.map.mapZoomCustom=jvh.map.regCountryMapZoom;var e,t;"resort"==jvh.destinations.pageClass||"holiday-resort"==jvh.destinations.pageClass?(e=resorts2[jvh.destinations.destSettings.id],t=15):"region"==jvh.destinations.pageClass?(e=regions2[jvh.destinations.destSettings.id],t=8):"region-group"==jvh.destinations.pageClass?(e=regionGroups2[jvh.destinations.destSettings.id],t=6):"country"==jvh.destinations.pageClass&&(e=countries2[jvh.destinations.destSettings.id],t=6),e.marker.setMap(jvh.map.map);
    var a=new google.maps.LatLng(e.lat,e.lng);jvh.map.map.setCenter(a),jvh.map.map.setZoom(t)},mapHideShow:function(){jvh.map.mapZoomCustom=jvh.map.regCountryMapZoom,jvh.map.hideShowItems(resorts1,3==jvh.map.currentZoomLevel),jvh.map.hideShowItems(regions1,2==jvh.map.currentZoomLevel),jvh.map.hideShowItems(regionGroups1,1==jvh.map.currentZoomLevel),jvh.map.hideShowItems(countries1,1==jvh.map.currentZoomLevel)
    },beachCarousel:function(e){var t="";for(t+='<aside class="beach-golf-container beach">',t+='<button class="close">X</button>',t+='<ul class="beach-golf" data-track-label="Beaches" data-track-category="Beaches carousel">',i=0;e.length>i;++i){t+='<li class="beach-'+e[i].villaGroupId+'" data-map-object="jvh.destinations.map.beaches" data-id="'+e[i].villaGroupId+'">',beachImage=""!=e[i].beachThumb?e[i].beachThumb:jvh.core.settings.imageDomain+"/images/jvh/layout/resort/placeholder_beach_image.jpg",t+='<div class="image-block"><img src="'+beachImage+'" alt="'+e[i].beachName+" in "+e[i].resortName+'"><h3>'+e[i].beachName+", "+e[i].resortName+"</h3></div>",t+='<div class="jvh-scroll-fade"><div class="content-info">';
    var a=!1;(""!=e[i].beachAccess||""!=e[i].beachParking)&&(t+="<h4>Access to the Beach:</h4>",""!=e[i].beachAccess&&(t+="<p>"+e[i].beachAccess+"</p>"),""!=e[i].beachParking&&(t+="<h5>Parking: </h5><p>"+e[i].beachParking+"</p>"),a=!0),""!=e[i].beachType&&(t+="<h4>Beach type:</h4>",t+="<p>"+e[i].beachType+"</p>",a=!0),""!=e[i].beachSafety&&(t+="<h4>Beach safety:</h4>",t+="<p>"+e[i].beachSafety+"</p>",a=!0),(""!=e[i].chargedFacilities||""!=e[i].freeFacilities||""!=e[i].otherFacilities)&&(t+="<h4>Facilities:</h4>",""!=e[i].chargedFacilities&&(t+="<h5>Charged facilities: </h5><p>"+e[i].chargedFacilities+"</p>"),""!=e[i].freeFacilities&&(t+="<h5>Free facilities: </h5><p>"+e[i].freeFacilities+"</p>"),""!=e[i].otherFacilities&&(t+="<p>"+e[i].otherFacilities+"</p>"),a=!0),""!=e[i].activities&&(t+="<h4>Activities for hire:</h4>",0/0+e[i].activities+"</p>",a=!0),(""!=e[i].beachFrontFood||""!=e[i].walkingDistanceFood||""!=e[i].foodOther)&&(t+="<h4>Food/Drink:</h4>",""!=e[i].beachFrontFood&&(t+="<h5>Beach front: </h5><p>"+e[i].beachFrontFood+"</p>"),""!=e[i].freeFacilities&&(t+="<h5>Walking distance: </h5><p>"+e[i].walkingDistanceFood+"</p>"),""!=e[i].foodOther&&(t+="<p>"+e[i].foodOther+"</p>"),a=!0),""!=e[i].beachOther&&null!=e[i].beachOther&&(t+="<h4>Other:</h4><p>"+e[i].beachOther+"</p>",a=!0),a&&""!=e[i].lastUpdated&&(t+='<div class="caveat">Information updated '+e[i].lastUpdated+"</div>"),a||(t+='<div class="comingSoon">Beach information coming soon.</div>'),t+="</div></div></li>"
    }t+="</ul>",t+="</aside>",$("section.map-content").append(t)},golfCarousel:function(e){var t="";for(t+='<aside class="beach-golf-container golf">',t+='<button class="close">X</button>',t+='<ul class="beach-golf" data-track-label="Golf" data-track-category="Golf carousel">',i=0;e.length>i;++i){t+='<li class="golf-'+e[i].villaGroupId+'" data-map-object="jvh.destinations.map.activities" data-id="'+e[i].villaGroupId+'">',golfImage=""!=e[i].golfThumb?e[i].golfThumb:jvh.core.settings.imageDomain+"/images/jvh/layout/resort/placeholder_golf_image.jpg",t+='<div class="image-block"><img src="'+golfImage+'" alt="'+e[i].golfName+" in "+e[i].resortName+'"><h3>'+e[i].golfName+", "+e[i].resortName+"</h3></div>",t+='<div class="jvh-scroll-fade"><div class="content-info">';
    var a=!1;if(""!=e[i].information){for(courses=e[i].information.split(", "),t+="<h4>Course information:</h4>",x=0;courses.length>x;++x)t+="<p>"+courses[x]+"</p>";
    a=!0}""!=e[i].restrictions&&(t+="<h4>Restrictions:</h4>",null!=e[i].courseAges&&(t+="<h5>Age requirements :</h5><p>"+e[i].courseAges+"</p>"),t+="<p>"+e[i].restrictions+"</p>",a=!0),""!=e[i].facilities&&(t+="<h4>Course facilities:</h4>",t+="<p>"+e[i].facilities+"</p>",a=!0),a&&""!=e[i].lastUpdated&&(t+='<div class="caveat">Information updated '+e[i].lastUpdated+"</div>"),a||(t+='<div class="comingSoon">Golf information coming soon.</div>'),t+="</div></div></li>"
    }t+="</ul>",t+="</aside>",$("section.map-content").append(t)}},resortAccomSection:{pageFirstRun:!0,currentBedrooms:0,currentAccomCount:0,resortAccom:Array(),bedroomList:Array(),bedroomOptionLength:0,init:function(){var e=jvh.destinations;
    if(e.resortAccomSection.pageFirstRun){var t=$("ul.pagination-controls");jvh.core.pagination.init(t,e.resortAccomSection.init),$("#bedroomSelect").on("change",function(){e.resortAccomSection.showBedrooms($(this).val()),jvh.core.images.lazyLoad($(".resort-accom"))
    })}e.resortAccomSection.showAccom(),e.resortAccomSection.pageFirstRun=!1,jvh.core.images.lazyLoad($(".resort-accom")),jvh.core.tracking.autoTrack($("ul.pagination-controls"))
    },accom:function(e,t,a){this.id=e,this.bedrooms=t,this.display=!0,this.paginated=!1,this.imgSrc=a},addAccom:function(e,t,a){jvh.destinations.resortAccomSection.resortAccom[jvh.destinations.resortAccomSection.resortAccom.length]=new jvh.destinations.resortAccomSection.accom(e,t,a),jvh.destinations.resortAccomSection.bedroomList[t]=1
    },addBedroom:function(e){var t=document.createElement("option");return t.value=e,t.text=1==e?"1 bedroom":e+" bedrooms",t
    },buildBedroomLinks:function(){var e=$("#bedroomSelect");e.find("option:gt(0)").remove();for(var t=jvh.destinations,a=1;t.resortAccomSection.bedroomList.length>=a;a++)1==t.resortAccomSection.bedroomList[a]&&(e.append(t.resortAccomSection.addBedroom(a)),t.resortAccomSection.bedroomOptionLength++);
    $("#bedroomSelect option[value="+t.resortAccomSection.currentBedrooms+"]").attr("selected","selected")
    },showBedrooms:function(e){var t=jvh.destinations;t.resortAccomSection.currentBedrooms=parseInt(e),$("ul.pagination-controls").data("current-page",1),t.resortAccomSection.init()
    },buildResultsText:function(e,t){var a=jvh.destinations;t>a.resortAccomSection.currentAccomCount&&(t=a.resortAccomSection.currentAccomCount);
    var i="";i=1>=a.resortAccomSection.currentAccomCount?a.resortAccomSection.currentAccomCount+" of "+a.resortAccomSection.currentAccomCount:e+1+" - "+t+" of "+a.resortAccomSection.currentAccomCount,$(".results-count").html(i)
    },showAccom:function(){var e=0,t=0,a=0,i=jvh.destinations,o=i.resortAccomSection.currentAccomCount;i.resortAccomSection.currentAccomCount=0;
    var s,n,r=$("ul.pagination-controls"),c=r.data("per-page"),l=!1;s=c*(r.data("current-page")-1),n=s+c;
    for(var d=0;i.resortAccomSection.resortAccom.length>d;d++){0===i.resortAccomSection.currentBedrooms||i.resortAccomSection.resortAccom[d].bedrooms==i.resortAccomSection.currentBedrooms?(i.resortAccomSection.resortAccom[d].display=!0,i.resortAccomSection.currentAccomCount++):i.resortAccomSection.resortAccom[d].display=!1,i.resortAccomSection.resortAccom[d].paginated=!1,i.resortAccomSection.resortAccom[d].display&&(e>=s&&n>e?t++:i.resortAccomSection.resortAccom[d].display=!1,i.resortAccomSection.resortAccom[d].paginated=!0,e++);
    var v=$("#accom"+i.resortAccomSection.resortAccom[d].id);i.resortAccomSection.resortAccom[d].display?(a++,v.addClass("active")):v.removeClass("active")
    }var h=$("ul.resort-accom");$(".filler-element").remove(),modBy="desktop"==jvh.core.viewport?4:"tablet"==jvh.core.viewport?3:1;
    var m=i.resortAccomSection.currentAccomCount%modBy;0!=m&&h.append('<li class="filler-element active"></li><li class="filler-element active"></li>'),i.resortAccomSection.buildBedroomLinks(),i.resortAccomSection.buildResultsText(s,n),i.resortAccomSection.currentAccomCount!=o&&(l=!0),jvh.core.pagination.refreshPagination($("ul.pagination-controls"),i.resortAccomSection.currentAccomCount,l),2>=i.resortAccomSection.bedroomOptionLength?$(".accom-filters").addClass("hidden"):($(".accom-filters").removeClass("hidden"),$(".bedroom-select").addClass("visible"))
    }},events:{resortEvents:Array(),init:function(){jvh.destinations.events.buildLists();var e=jvh.destinations;
    $(".psuedo-calendar").on("click","li.event",function(){var t=$(this),a=t.attr("id"),i="opened";t.hasClass("active")?(i="closed",t.removeClass("active"),"mobile"==jvh.core.viewport&&$(".mobile-desc",t).removeClass("active")):($(".events-container li.event").removeClass("active"),t.addClass("active"),"mobile"!=jvh.core.viewport?e.events.populateEvent(a):$(".mobile-desc",t).addClass("active")),jvh.core.tracking.trackEvent(jvh.core.trackingType,"Event - "+t.find("> p").text()+" - "+i,"Events block")
    }),$(".psuedo-calendar").on("click","li.day, li.month",function(){if("mobile"!=jvh.core.viewport){var e=$(this),t=e.data("event-month"),a="month",i="opened";
    t===void 0&&(t=e.data("event-day"),a="day"),$(".mobile-desc").removeClass("active");var o=e.parent("ul").find("li.active.event"),s=e.parent("ul").find("li.event.visible");
    o.removeClass("active"),s.removeClass("visible"),e.hasClass("active")?(i="closed",$(this).parent("ul").find("li.event."+t).each(function(e){var t=$(this);
    window.setTimeout(function(){t.removeClass("visible")},80*e)}),e.parent("ul").find("li.active."+a).removeClass("active")):(e.parent("ul").find("li.active."+a).removeClass("active"),e.addClass("active"),$(this).parent("ul").find("li.event."+t).each(function(e){var t=$(this);
    window.setTimeout(function(){t.addClass("visible")},100*e)})),jvh.core.tracking.trackEvent(jvh.core.trackingType,"Event "+a+" - "+e.find(".month-info span").text()+" - "+i,"Events block")
    }}),$(".psuedo-calendar ul:first-of-type").addClass("active"),"mobile"==jvh.core.viewport&&($(".psuedo-calendar form:first-of-type").addClass("active"),$(".psuedo-calendar > ul > li:first-of-type").addClass("active")),$("#eventViewSelect").on("change",function(){var e=$(this);
    $(".psuedo-calendar > ul").removeClass("active"),$(".psuedo-calendar > ul > li").removeClass("active visible");
    var t=$("ul."+e.val());t.addClass("active"),"mobile"==jvh.core.viewport?($("#monthlyEvents, #weeklyEvents").removeClass("active"),t.find("> li:first-of-type").addClass("active"),$("#"+e.val()+"Events").addClass("active"),$("#monthlyEvents option:first, #weeklyEvents option:first").prop("selected",!0),$(".psuedo-calendar > ul > li:first-of-type").addClass("active")):$(".psuedo-calendar ul.active li.month, .psuedo-calendar ul.active li.day").each(function(e){var t=$(this);
    window.setTimeout(function(){t.addClass("visible")},100*e)})}),$("#monthEventsSelect, #weekEventsSelect").on("change",function(){var e=$(this),t=$(".psuedo-calendar ul > li."+e.val()).closest("ul");
    t.find("> li").removeClass("active visible"),$(".psuedo-calendar ul > li."+e.val()).addClass("active")
    });var t={items:1,center:!0,loop:!1,nav:!0,dots:!1,navText:["",""],autoWidth:!1,responsive:{0:{items:1},480:{items:3,center:!1,margin:3}}},a=$(".mob-events");
    a.data("settings",t),"mobile"==jvh.core.viewport&&a.owlCarousel(t)},fillerEventSquares:function(e){if("mobile"!=jvh.core.viewport){ulLength=$(e+" > li").length,fillers=28-ulLength;
    for(var t=0;fillers>t;t++){var a=Math.floor(Math.random()*ulLength+1);$(e+" > li:eq("+a+")").after('<li class="spacer"></li>')
    }}else $(e).find("li.spacer").remove()},populateEvent:function(e,t){var a='<div class="event-display">',i=$("#"+e),o="local",s=jvh.destinations;
    if(s.events.resortEvents[e].isNational&&(o="national"),t===void 0&&(t=!0),i.hasClass("monthly")?""!=s.events.resortEvents[e].eventFrom&&(date=s.events.resortEvents[e].eventFrom,""!=s.events.resortEvents[e].eventTo&&(date+=" - "+s.events.resortEvents[e].eventTo),a+='<p class="heading-small">'+date+"</p>"):""!=s.events.resortEvents[e].monthFrom&&(date=s.events.resortEvents[e].day+": "+s.events.resortEvents[e].monthFrom,""!=s.events.resortEvents[e].monthTo&&s.events.resortEvents[e].monthTo!=s.events.resortEvents[e].monthFrom&&(date+=" - "+s.events.resortEvents[e].monthTo),a+='<p class="heading-small">'+date+"</p>"),a+='<span class="'+o+'">'+o+" event</span>",a+="<h3>"+s.events.resortEvents[e].name+"</h3>",""!=s.events.resortEvents[e].description&&(a+='<div class="jvh-scroll-fade">'+s.events.resortEvents[e].description+"</div>"),a+='<div class="cycle-controls">',a+="<span class=\"next-button\" data-key-right='true'></span>",a+="<span class=\"prev-button\" data-key-left='true'></span>",a+="</div>",a+="</div>",$(".psuedo-calendar li.event").removeClass("active"),t)jvh.core.showInnerModal($("div.events-content"),a,i);
    else{var n=$(".inner-modal");$(".event-display").remove(),n.append(a)}var r=i.nextAll("li.event.visible"),c=i.prevAll("li.event.visible");
    0==r.length&&0==c.length?$(".cycle-controls").addClass("disabled"):(0==r.length&&$(".cycle-controls .next-button").addClass("disabled"),0==c.length&&$(".cycle-controls .prev-button").addClass("disabled")),$(".cycle-controls").on("click",".next-button, .prev-button",function(e,t){e.preventDefault();
    var a=$(this),i="";a.not(".disabled").hasClass("next-button")?(jvh.destinations.events.populateEvent(r.attr("id"),!1),i="next"):a.not(".disabled").hasClass("prev-button")&&(jvh.destinations.events.populateEvent(c.attr("id"),!1),i="prev"),void 0==t&&(t="Clicked"),jvh.core.tracking.trackEvent(jvh.core.trackingType,t+" "+i,"Events block")
    })},event:function(e,t,a,i,o,s,n,r,c,l){this.id=e,this.name=t,this.isNational=a,this.description=i,this.eventFrom=o,this.eventTo=s,this.eventFrequency=n,this.monthFrom=r,this.monthTo=c,this.day=l
    },addEvent:function(e,t,a,i,o,s,n,r,c,l){jvh.destinations.events.resortEvents[e]=new jvh.destinations.events.event(e,t,a,i,o,s,n,r,c,l)
    },buildLists:function(){var e=jvh.destinations;"mobile"!=jvh.core.viewport?($("ul.monthly > li.event").remove(),$("ul.monthly li.month").each(function(){var e=$(this),t=e.find("ul.mob-events li").clone();
    e.after(t)}),e.events.fillerEventSquares(".psuedo-calendar ul.monthly"),$("ul.weekly > li.event").remove(),$("ul.weekly li.day").each(function(){var e=$(this),t=e.find("ul.mob-events li").clone();
    e.after(t)}),e.events.fillerEventSquares(".psuedo-calendar ul.weekly")):$("ul.monthly > li.event, ul.weekly > li.event").remove()
    }},resortInView:function(){var e=0;if(e="mobile"!=jvh.core.viewport?200:0,jvh.core.isInView(".resort-promotions",e)){$(".resort-promos > li").each(function(e){var t=$(this);
    t.hasClass("promo-filler")||t.removeClass("display-none"),window.setTimeout(function(){t.addClass("visible")
    },100*e)}),modBy="mobile"!=jvh.core.viewport?3:1;var t=$(".resort-promos > li:not(.promo-filler)").length%modBy;
    0!=t&&($(".resort-promotions .promo-filler").removeClass("display-none"),jvh.core.images.lazyLoad($(".promo-filler")))
    }},closeBeachGolf:function(){$(".beach-golf-container").removeClass("active");for(var e=0;jvh.map.selectedMarker.length>e;e++)jvh.map.selectedMarker[e].setIcon(jvh.map.getIcon(jvh.map.selectedMarker[e].type,!1,!1,jvh.map.selectedMarker[e].content))
    }},jvhWaitForJs(["core"],jvh.destinations.init),jvh.data.jsLoaded.destinations=!0,jvhTriggerEvent("destinations-jsLoaded");
    
    //@ sourceMappingURL=min/destinations-min.js.map